### ISSUE TITLE
Implement Menu System For Header

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/wds-react#5]
### 💡 Description

The menus in the header do not appear when clicked. Need to add that functionality.

### ⚔️ Parent Epic / Related Tickets

https://github.com/NASA-PDS/portal-wp-tasks/issues/55

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo spent some time to comply with NASA requirements to have a single click to switch from one menu to another.

**Comment by jordanpadams** [comment]
Closed on header branch
