### ISSUE TITLE
Update Iconography For Header

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/wds-react#6]
### 💡 Description

Implement the icons and their changes for the header.

**Comment by tloubrieu-jpl** [comment]
In progress.

**Comment by tloubrieu-jpl** [comment]
Still in progress, @eddiesarevalo is looking at how to build the repo.

**Comment by tloubrieu-jpl** [comment]
There is an issue to generate the icons which does not work with one of the library used otherwise to build the project.

**Comment by jordanpadams** [comment]
Status: Ran into some issues. Trying out a couple different solutions to debug.

**Comment by tloubrieu-jpl** [comment]
A fix has been done on react-styler which unblocked @eddiesarevalo and enabled to create the icons.
