### ISSUE TITLE
Show Search Results With PDS Styles

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/wds-react#69]
## 💪 Motivation
I want to see these json results https://pds.nasa.gov/api/search-en-gamma/1.1/classes/collections??keyword=mars&wt=json in PDS styles

## 📖 Additional Details
The api results are returned in JSON. Style the results to show human readable as stated in the designs:![Screen Shot 2022-11-29 at 12.49.40 PM.png](https://images.zenhubusercontent.com/5e98a8928301b57ff5d93d52/94845c6b-5425-469e-8bd8-c61d9a54ae91)

## ⚖️ Acceptance Criteria
The json results should look similar to the screen shot of the designs above.

## ⚙️ Engineering Details
Use material ui components to show a similar layout to the designs.

**Comment by eddiesarevalo** [comment]
Showing results like this now:
![Screen Shot 2022-12-07 at 12 39 49 PM](https://user-images.githubusercontent.com/5596893/206291519-4ca74ce7-357e-48ba-8946-2051ec180353.png)

Need to clarify some details from @edwardbarraza when he gets back.

Used a caret instead of an circle arrow as shown here. There aren't any in material ui.
<img width="860" alt="Screen Shot 2022-12-07 at 12 46 33 PM" src="https://user-images.githubusercontent.com/5596893/206292187-fda82696-8284-4dc8-a682-fd825a67927b.png">

**Comment by eddiesarevalo** [comment]
Will continue #77

**Comment by tloubrieu-jpl** [comment]
The code is available in wds-react repository in the main branch
