### ISSUE TITLE
Update Header Styles

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/wds-react#7]
### 💡 Description

The styles need to be updated to match more closely to the figma designs.

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo is starting to use SASS instead of material UI.

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo need to meet with @anilnatha to validate the CSS options.

**Comment by tloubrieu-jpl** [comment]
plain CSS are going to be used.

@eddiesarevalo is adding the needed style in the wds repository. It is a manual task.

**Comment by tloubrieu-jpl** [comment]
colors and typos have been added.

**Comment by tloubrieu-jpl** [comment]
The styles have been added.

**Comment by eddiesarevalo** [comment]
Added the variables to the wds https://github.com/NASA-PDS/wds/commit/d3d680f30285d285a0c733fab88784c2306dbb41
