### ISSUE TITLE
Move Header Code From Wordpress Repo To React Repo

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/wds-react#8]
### 💡 Description

Need to move over the header code from the wordpress repo to the react repo. This requires some code changes and reorganization. 

The header will need to be available through the library install.

**Comment by tloubrieu-jpl** [comment]
This ticket is almost done.

**Comment by tloubrieu-jpl** [comment]
Available in branch develop with commit b7cc76281e87fd7a8facac26c6f42695f4f857ad
